services:
  - type: web
    name: singingbowlandgonghouse
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn SingingBallAndGongHouse.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "SingingBallAndGongHouse.settings"
